# Generated by Django 3.1.2 on 2020-10-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('corona', models.TextField(help_text='Enter coronavirus restriction information.', max_length=10000)),
                ('quarantine', models.TextField(help_text='Enter quarantine restriction information', max_length=10000)),
                ('inbound', models.TextField(help_text='Enter inbround quarantine restriction information', max_length=10000)),
                ('date_of_information', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
