# Generated by Django 3.1.2 on 2020-10-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='inbound',
        ),
    ]
