# Generated by Django 3.1.2 on 2020-10-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_remove_country_inbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='inbound_country_name',
            field=models.CharField(blank=True, help_text='Enter name of countries on inbound travel corridor list.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='sentiment',
            field=models.FloatField(blank=True, help_text='Sentiment classification score', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='date_of_information',
            field=models.DateField(blank=True, help_text='Enter the date information was acquired.', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Enter the country name.', max_length=200),
        ),
    ]
